name: Release
on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  REPO_OWNER: ${{ github.repository_owner }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  terraform:
    name: Execute Terraform
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: configs/terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ~1.0

      - name: Terraform Init
        run: terraform init -backend-config="conn_str=postgres://${{ secrets.TF_STATE_DB_USERNAME }}:${{ secrets.TF_STATE_DB_PASSWORD }}@${{ secrets.TF_STATE_DB_HOST }}:${{ secrets.TF_STATE_DB_PORT }}/${{ secrets.TF_STATE_DB_NAME }}?sslmode=disable"

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false
        env:
          TF_WORKSPACE: prod
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy API
    runs-on: ubuntu-latest
    environment: production
    needs: [terraform]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy api
        run: |
          flyctl deploy --now -a prod-nba-stats-api \
            -i ${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/nba-stats-api:${{ github.sha }} \
            -e NBA_BASE_URL=https://stats.nba.com \
            -e NBA_CDN_BASE_URL=https://cdn.nba.com \
            -e WNBA_CDN_BASE_URL=https://cdn.wnba.com
